require 'vedeu/geometry/area'
require 'vedeu/geometry/coordinate'
require 'vedeu/geometry/dimension'

require 'vedeu/geometry/geometry'
require 'vedeu/repositories/store'
require 'vedeu/repositories/registerable'
require 'vedeu/repositories/repository'
require 'vedeu/geometry/geometries'
require 'vedeu/geometry/grid'
require 'vedeu/geometry/index_position'
require 'vedeu/geometry/position_index'
require 'vedeu/geometry/position'
require 'vedeu/geometry/position_validator'
