AllCops:
  Include:
    - '**/*.gemspec'
    - '**/*.podspec'
    - '**/*.jbuilder'
    - '**/*.rake'
    - '**/*.opal'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Capfile'
    - '**/Guardfile'
    - '**/Podfile'
    - '**/Thorfile'
    - '**/Vagrantfile'
    - '**/Berksfile'
    - '**/Cheffile'
    - '**/Vagabondfile'
  Exclude:
    - 'benchmarks/**/*'
    - 'examples/**/*'
    - 'integrations/**/*'
    - 'test/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true
  DisplayStyleGuide: true
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.4

Security/Eval:
  Description: 'The use of eval represents a serious security risk.'
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Style/AsciiComments:
  Description: 'Use only ascii symbols in comments.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#english-comments'
  Enabled: false

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  EnforcedStyle: no_empty_lines

Style/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Style/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines

Style/MultilineBlockChain:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/SpaceAroundOperators:
  Enabled: false

Style/TrailingBlankLines:
  EnforcedStyle: final_newline

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Metrics/AbcSize:
  Max: 25

Metrics/ClassLength:
  Description: 'Avoid classes longer than 100 lines of code.'
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/MethodLength:
  CountComments: false
  Max: 30

Metrics/ModuleLength:
  Max: 200

Metrics/PerceivedComplexity:
  Max: 10
