require 'vedeu/repositories/repository'

require_relative 'colours'
require_relative 'background_colours'
require_relative 'foreground_colours'
require_relative 'borders'
require_relative 'buffers'
require_relative 'cursors'
require_relative 'events'
require_relative 'geometries'
require_relative 'groups'
require_relative 'interfaces'
require_relative 'keymaps'
require_relative 'menus'
