require 'io/console'
require 'singleton'
require 'timeout'

require 'vedeu/colours/base'
require 'vedeu/colours/foreground'
require 'vedeu/colours/background'

require 'vedeu/colours/colour'
require 'vedeu/colours/custom'
require 'vedeu/colours/palette'
require 'vedeu/colours/style'
require 'vedeu/colours/translator'
require 'vedeu/colours/wrapper'

require 'vedeu/composition/grid'
require 'vedeu/composition/row'

require 'vedeu/input/character/multibyte'
require 'vedeu/input/character/standard'
require 'vedeu/input/keyboard'
require 'vedeu/input/sequence'
require 'vedeu/input/translator'
require 'vedeu/input/wrapper'

require 'vedeu/buffer'
require 'vedeu/clock'
require 'vedeu/d_buffer'
require 'vedeu/esc'
require 'vedeu/renderer'
require 'vedeu/terminal'
require 'vedeu/version'
