#!/usr/bin/env ruby
$:.unshift(File.dirname(__FILE__) + '/../lib') unless $:.include?(File.dirname(__FILE__) + '/../lib')

-> { its -> { a } }
trap('INT') { exit! }

require 'vedeu'

# stream = [
#   [
#     [
#       [],
#       'Lorem ipsum dolor sit amet, consectetur adipiscing'
#     ],[
#       [],
#       'elit. Cras sed ipsum ut purus imperdiet molestie'
#     ],[
#       [],
#       'in id neque. Sed auctor venenatis ultrices. Morbi'
#     ],[
#       [],
#       'ullamcorper libero et euismod malesuada. Aliquam'
#     ],[
#       [],
#       'dignissim metus eget tellus condimentum, ac dictum'
#     ],[
#       [],
#       'enim posuere. Curabitur posuere arcu elementum'
#     ],[
#       [],
#       'rutrum pulvinar. Nullam et dui eu lectus'
#     ],[
#       [],
#       'sollicitudin hendrerit eu at nibh. Cum sociis.'
#     ]
#   ]
# ]

stream = [
  [
    [[:underline, "test1"],
    [[[:red, :black]], "test2"],
    [[], "test3"]
  ]
]

geometry  = { geometry: { y: 0, x: 0, width: 50, height: 15 } }
interface = Vedeu::Interface.new(geometry)

Vedeu::Compositor.write(stream, interface)

print "\n"
