require 'vedeu/repositories/buffers'
require 'vedeu/repositories/cursors'
require 'vedeu/repositories/events'
require 'vedeu/repositories/focus'
require 'vedeu/repositories/groups'
require 'vedeu/repositories/interfaces'
require 'vedeu/repositories/keymaps'
require 'vedeu/repositories/menus'
