require 'vedeu/models/collection'

require 'vedeu/models/buffer'
require 'vedeu/models/char'
require 'vedeu/models/composition'
require 'vedeu/models/cursor'
require 'vedeu/models/event'
require 'vedeu/models/geometry'
require 'vedeu/models/group'
require 'vedeu/models/interface'
require 'vedeu/models/line'
require 'vedeu/models/menu'
require 'vedeu/models/model'
require 'vedeu/models/stream'
